site_name: Bild Development Getting Started
nav:
  - Home: index.md
  - Setup:
      - Git: git.md
      - Java JDK: jdk.md
      - Eclipse / STS: eclipse.md
      - Visual Studio Code: vscode.md
      - VS Code Extensions: extensions.md
  - Study Resources: resources.md
# theme: readthedocs
theme:
  name: mkdocs
  user_color_mode_toggle: true
