site_name: Bild Development Getting Started
nav:
  - Home: index.md
  - Git: git.md
  - JDK: jdk.md
  - Eclipse: eclipse.md
  - VsCode: vscode.md
  - Extensions: extensions.md
  - Resourses: resourses.md
# theme: readthedocs
theme:
  name: mkdocs
  user_color_mode_toggle: true
